services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - EMAIL_USER_FROM=${EMAIL_USER_FROM}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USER_TO=${EMAIL_USER_TO}
    restart: always